---

- name: apt update
  apt:
    update_cache: yes
  become: true

- name: apt dist-upgrade
  apt:
    upgrade: dist
  become: true

- name: Reboot box if kernel/libs updated and requested by the system
  shell: sleep 10 && /sbin/shutdown -r now 'Rebooting box to update system libs/kernel as needed' 
  args:
      removes: /var/run/reboot-required
  async: 300
  poll: 0
  ignore_errors: true

- name: Wait for system to become reachable again
  wait_for_connection:
    delay: '45'
    timeout: '300'

- name: Verify new update (optional)
  command: uname -mrs
  register: uname_result
- name: Display new kernel version
  debug:
      var: uname_result.stdout_lines
